type Board {
  id: String!
  title: String!
  slug: String
  description: String
  owner: User
  createdAt: Float
}

scalar Date

type LoginToken {
  token: String!
}

type Mutation {
  login(email: String!, password: String, token: String): LoginToken
  createBoard(title: String!, description: String): Board
}

type Query {
  users(limit: Int, offset: Int, sort: String): [User]
  user(id: String): User
  me: User
  boards(limit: Int, offset: Int, sort: String): [Board]
  boardCount: Int
  board(id: String!): Board
}

type User {
  id: String!
  username: String!
  firstName: String!
  lastName: String!
  email: String
  avatar: String
  status: Int
  boards(limit: Int, offset: Int, sort: String): [Board]
  boardCount: Int
}
