{
 "title": "Moleculer",
 "tags": [ "moleculer" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(moleculer_registry_nodes_online_total)"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(moleculer_registry_services_total)"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(moleculer_registry_actions_total)"
    }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(moleculer_registry_events_total)"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    { "expr": "sum(moleculer_request_total)" }
   ]
  },
  {
   "title": "Total errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(moleculer_request_error_total)"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(moleculer_request_time_rate)"
    }
   ]
  },
  {
   "title": "Req/min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(moleculer_request_total_rate)"
    }
   ]
  },
  {
   "title": "Transfer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(moleculer_transporter_packets_sent_bytes[1m])) * 8"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moleculer_request_time_sum[1m])) / avg(irate(moleculer_request_time_count[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moleculer_request_total[1m]))",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(irate(moleculer_request_error_total[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Received Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (event) (irate(moleculer_event_received_total[1m]))",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (irate(moleculer_request_total[1m]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Tx/Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moleculer_transporter_packets_received_bytes[1m]))*8",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(irate(moleculer_transporter_packets_sent_bytes[1m]))*8",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Service to Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (caller,service) (irate(moleculer_request_total[1m]))",
     "legendFormat": "{{caller}}->{{service}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 25 } },
  {
   "title": "Available nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(moleculer_registry_nodes_total)"
    }
   ]
  },
  {
   "title": "Errors by types",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (errorName) (irate(moleculer_request_error_total[1m]))",
     "legendFormat": "{{errorName}}"
    }
   ]
  }
 ]
}